### ISSUE TITLE
Interceptor for brave

### ISSUE THREAD

**Issue by qzaidi** [httptoolkit/httptoolkit-server#10]
Is it possible to intercept brave the same way chrome is being intercepted - and launch it in place of chrome

**Comment by pimterry** [comment]
It's absolutely possible, it's just not implemented quite yet.

The main thing that needs doing is to collect the info required so we can detect whether Brave is installed. If you're a Brave user, any chance you could help with that?

For reference, the change required to detect the new Chromium-based Edge is here: https://github.com/httptoolkit/browser-launcher/commit/d10e68401c9429bb2d543b5efb895ca3bbc423ae?w=1. It looks like https://github.com/vweevers/win-detect-browsers does already supports Brave, so we're good for Windows at least.

To do Mac & Linux, I think we need:

* The `CFBundleVersion` for Brave on Mac (the CFBundleVersion for beta/canary releases too, if we want to support them as well, I don't know what kind of variants like that Brave has, or if anybody uses them)
* The name of the binary on Linux (`brave`, I guess?)
* A regex to extract the version from the output of `<brave binary> --version` on Linux

I'll try to take a look at this myself sometime soon, but if you've got any of the above details to hand then that'd definitely help get this implemented sooner :smiley:.

**Comment by qzaidi** [comment]
Thanks for so quick reply and considering the feature request, surely I can help with the CFBundleVersion on Mac. 

```
        <key>CFBundleVersion</key>
        <string>105.112</string>
        <key>CrProductDirName</key>
        <string>BraveSoftware/Brave-Browser</string>
```

The binary name on linux is indeed brave

This is the output from running --version on mac, I would guess linux will have similar output
/Applications/Brave\ Browser.app/Contents/MacOS/Brave\ Browser --version
Brave Browser 80.1.5.112

**Comment by pimterry** [comment]
![Screenshot from 2020-05-07 12-38-31](https://user-images.githubusercontent.com/1526883/81285347-ae5f5e80-905f-11ea-924e-8ec830aa7b32.png)

Now done and live, along with various other browser support improvements :+1:. Your app will update in the background next time it's started, and then pick it up the following run. It's still a bit experimental, so let me know if you hit any issues. Thanks for the suggestion!
