### ISSUE TITLE
possible to drop url and headers to a file ?

### ISSUE THREAD

**Issue by graysuit** [httptoolkit/httptoolkit-server#101]
First of all thanks for great httptoolkit tool, so much easier to use.

I want to intercept and extract specific header value(i.e Cookie) from specific url from android app.
Any way I edit any server file, so it drops url and headers to file ? So my program (dotnet) can access it. 

![image](https://github.com/httptoolkit/httptoolkit-server/assets/54432616/5dbc12bf-8509-44d3-a257-93c1af36dacf)

Any ideas ?
Thank you

**Comment by pimterry** [comment]
> Which part is responsible for displaying headers ?

There is no one line of code somewhere that's responsible for this, it's a complicated project spread across a lot of repos (you can see the full list [in the org](https://github.com/httptoolkit?q=&type=source&language=&sort=stargazers))

> Is that possible, if I can hack mockttp or httptoolkit-server code, edit any line, so it just drops out cookie ?

That's going to be a _lot_ more complicated that creating a quick proxy to do this, and I don't have time to walk you through it I'm afraid. Feel free if you want, but it's not the best approach.

Doing it in your own standalone script will be much simpler. It should be very easy, just follow the Mockttp guide to get setup, and then reading the cookies from all requests through that proxy is literally one line:

```
mockttpServer.on('request', (req) => console.log(req.headers.cookie));
```

In terms of the Android part - if you use HTTP Toolkit alongside Mockttp, you can use all the normal HTTP Toolkit setup stuff as always, and everything will work just like normal (but note that redirecting all traffic from HTTP Toolkit via an upstream proxy requires HTTP Toolkit Pro).

Alternatively, you can skip HTTP Toolkit and just use Mockttp + Android directly - you just need to manually configure your proxy & CA certificate on the Android device.

I can't offer detailed support on this though, it's quite complicated and I just don't have time. The Mockttp guide should be a good starting point. Do feel free to dig into the source here for yourself if you'd prefer, but be aware that changing the internals is likely to be tricky, and it'll be very easy to break things in strange and unpredictable ways.
