### ISSUE TITLE
Traffic not captured in Burp-suite after successful certificate install on Android 14 pixel 8 device

### ISSUE THREAD

**Issue by faisalbokhari** [httptoolkit/httptoolkit-server#135]
I have added the Burp suite certificate in my  rooted pixel 8 device as system trusted certificate and  it was added successfully and shown in UI with the a blue tick on it like all other certificates. But when I open the chrome or any other application burp suites  show TLS handshake error. What can be a root cause for this error?

**Comment by pimterry** [comment]
@faisalbokhari this doesn't make much sense - how does the Burp Suite certificate relate to HTTP Toolkit? Normally with HTTP Toolkit you wouldn't install the certificate manually at all, you'd use the automatic setup tools. Is there a reason you're not doing that?
