### ISSUE TITLE
Decrypt response to actual value in "/client/send" API

### ISSUE THREAD

**Issue by onecthree** [httptoolkit/httptoolkit-server#139]
The response from endpoint ```/client/send``` are contain JSON body:
```json
{
   "type": "response-body-part",
   "rawBody": "...encrypted value (base64?)..."
}
```
Is possible to decrypt this without the app UI? I try base64 decode but the result are random char. Thank you.

**Comment by pimterry** [comment]
It depends hugely on the actual content really! There's normally some info in the headers about what the content type is and what kind of encodings are used, but there's a huge range of possibilities here. Can you share any more detail about the response you're receiving?
