### ISSUE TITLE
README hyperlink to “src/api/rest-api.ts” points to “src/api/rest-server.ts” instead

### ISSUE THREAD

**Issue by AV306** [httptoolkit/httptoolkit-server#143]
Sorry for raising such a trivial issue, but I just wanted to let you know that the link to `src/api/rest-api.ts` on line 15 of the README actually points to `src/api/rest-server.ts`, instead of `rest-api.ts` :)

Thanks for all the work you’ve put into making HTTP Toolkit such an amazing and easy-to-use tool!

**Comment by pimterry** [comment]
Thanks for the heads up @AV306! Just FYI, in future you can just click the 'edit' icon in the top right of the readme and submit edits directly yourself :smiley:.

No worries though, I've just fixed that link now. Glad you're finding HTTP Toolkit useful, do let me know if you run into any other issues, big or small!
