### ISSUE TITLE
Fresh Terminal, Wrong git-bash

### ISSUE THREAD

**Issue by jonathansampson** [httptoolkit/httptoolkit-server#25]
One issue others may find is that HTTP Toolkit fails to open a _New Terminal Window_. In my case, the wrong `git-bash` command/file was being located. To identify which, I ran `Get-Command git-bash` in Powershell and found that an unexpected batch file was being accessed instead of my `git-bash.exe`.

To resolve the issue, I made sure my Git directory (`C:\Program Files\Git` in my case) was added to the Environment Variables, and positioned earlier than the directory which held the batch file with a similar name. This resolved the issue, enabling HTTP Toolkit to locate the proper executable.

https://github.com/httptoolkit/httptoolkit-server/blob/6c6249a752e17656843f0ceb204b89cedc9e7100/src/interceptors/terminal/fresh-terminal-interceptor.ts#L41-L49

The project presently uses command-exists, which [only checks `where`](https://github.com/mathisonian/command-exists/blob/742a73d75e6ff737c35aa7c88d0828cbb0455811/lib/command-exists.js#L64-L79). The lookpath project takes a slightly more rigorous approach, determining whether the path [is an _executable_](https://github.com/otiai10/lookpath/blob/9dbde74fbeb9dd9103d3dad2e5450d74b8d16aad/src/index.ts#L33-L37):

**Comment by pimterry** [comment]
Thanks for filing this @jonathansampson!

I've got a very quick fix in place already: https://github.com/httptoolkit/httptoolkit-server/commit/246a044b05575252e1fba930942d56a8ae129d25.

That'll work for this exact situation, by prioritising normal git-bash installs over random things in your $PATH. There's all sorts of other edge cases though (e.g. `git-bash` in PATH but not actually installed at all) so I do intend to harden this up further. It's not released yet, but that'll go out in the next server update.

> The project presently uses command-exists, which only checks where. The lookpath project takes a slightly more rigorous approach, determining whether the path is an executable:

This is a very good point! I'll take a look at lookpath and see if I can use that to filter this down further, and maybe get a perf boost if I can avoid lots of spawning too.

I'd also like to get "Existing Terminal" working on Windows, eventually, which'll help with this. On Linux and Mac, you can use that and copy a bash command into a terminal to intercept _any_ terminal, so launch heuristics don't matter so much. On Windows that's difficult though: most terminals aren't bash-compatible, and git bash & WSL transforms all the file paths which makes it complicated to generate the right env vars.

**Comment by jonathansampson** [comment]
Preferring the default bash path is a great change. Thanks!

**Comment by pimterry** [comment]
Just to let you know - the fix above and the switch over to lookpath was released recently, which should help with this. Thanks for the report & suggestions!

HTTP Toolkit will update automatically in the background next time you use it, and then everything will work as expected. I'm going to close this issue for now since that resolves the immediate problem, but let me know if you see any other issues in future.
