### ISSUE TITLE
self-signed upstream CA-certificate

### ISSUE THREAD

**Issue by madzodiac** [httptoolkit/httptoolkit-server#41]
I need to use a self-signed upstream CA-certificate within httptoolkit and couldn't find a place where to add this within the httptoolkit stack. Is there a place, like cacerts within jre where a self-signed root cert can be added?

**Comment by pimterry** [comment]
Yes, this exists but it's a Pro feature. If you have Pro, on the Settings page under "Connection Settings" you can add trusted CA certificates, or disable certificate validation for a hostname entirely.
