### ISSUE TITLE
Upstream proxy support

### ISSUE THREAD

**Issue by hacker1024** [httptoolkit/httptoolkit-server#44]
Could a method to set an upstream proxy server be added? Either through the CLI or with an environment variable?

**Comment by pimterry** [comment]
This is available, for HTTP, HTTPS and SOCKS4 & SOCKS5 proxies - it's a Pro feature, available in the Pro settings:

![Screenshot from 2022-05-02 14-00-41](https://user-images.githubusercontent.com/1526883/166230393-03a92aa0-634a-4fc1-911c-93cef895d4b6.png)

You can see the list of Pro features here: https://httptoolkit.tech/pricing/
