### ISSUE TITLE
Playground won't load

### ISSUE THREAD

**Issue by OliverCole** [httptoolkit/httptoolkit-server#6]
I set `playground: true` in `src/httptoolkit-server.ts`, but http://localhost:45457/ just returns `Cannot GET /`.

Any ideas?

**Comment by pimterry** [comment]
Good find: that's a documentation mistake, now fixed.

The valid values are actually `false`, or the path the playground should run at. If you replace `playground: true` with `playground: '/'` then http://localhost:45457/ should work fine. Thanks for reporting it!
