### ISSUE TITLE
Support darwin-arm64

### ISSUE THREAD

**Issue by shirshak55** [httptoolkit/httptoolkit-server#66]
Tracking issue to support m1 version of macos. 

Should we wait for GitHub to support the m1 version of actions? Also, it would be nice if we can publish a way to compile and build httptoolkit desktop app without fetching server from github release section?

**Comment by pimterry** [comment]
Good move, yes let's do this. As in my other comment - I've just bought an M1 Mac Mini so I can test this myself now.

> Should we wait for GitHub to support the m1 version of actions?

That would definitely help for automated testing, but I don't think it's strictly necessary, as far as I can tell it's possible to build everything we'll need from x86.

> Also, it would be nice if we can publish a way to compile and build httptoolkit desktop app without fetching server from github release section?

I'm not sure what you mean. Is there a specific reason for that? We do somehow need to download the server from somewhere at some point.

If you want to pull no server at all, and use your own raw development version (and your own development UI) you can run `npm run start:dev` in the desktop repo to launch the desktop shell totally by itself, without the server or hosted UI.

---

I think the next steps for this are:

- [ ] Update node-datachannel to a new version that works on ARM again (undo https://github.com/httptoolkit/httptoolkit-server/commit/2d81da45086efd1390176be63cbbdb09ee998995)
- [ ] Make sure it creates server builds that work everywhere (previously that change broke on Windows)
- [ ] Check for other native modules and make sure those include prebuilds too
- [ ] Confirm the resulting server builds run OK on M1
- [ ] Update the desktop to build separate Intel & M1 Mac builds, using the appropriate server for each
- [ ] Update the website to offer the correct build depending on the user

We could create a fully universal Mac build apparently, but I think due to Electron limitations it would be nearly double the size of the individual builds. Seems like we should be able to offer them separately instead in most cases I'd expect.

**Comment by pimterry** [comment]
I was planning to look into this myself, but if you're especially interested then any help on those steps is very welcome :smile:

**Comment by pimterry** [comment]
I've now updated MockRTC & node-datachannel again, with new versions that should include prebuilds for all platforms. That hopefully means that darwin-arm64 will now work out of the box for local dev!

I'm also currently fixing the distributable tests that should've caught the previous Windows issue here in release builds, and testing out building a specific darwin-arm64 release build too, but that'll take a little longer to properly investigate & set up.

If you get a minute @shirshak55, can you check out the latest version of this repo, do a fresh `npm install`, and check everything now works on your machine? I've tested for myself and so far it looks good but I want to be cautious to confirm 100% before the next release.

**Comment by shirshak55** [comment]
@pimterry is it working for you?

```
git pull
Already up to date.
npm i
npm WARN deprecated request-promise-native@1.0.5: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.3: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 2
npm ERR! path /Users/q/Desktop/projects/httptoolkit/httptoolkit-server/node_modules/node-datachannel
npm ERR! command failed
npm ERR! command sh -c -- prebuild-install || (npm install --ignore-scripts && npm run _prebuild)
npm ERR! added 601 packages, removed 1 package, and audited 659 packages in 5s
npm ERR!
npm ERR! 68 packages are looking for funding
npm ERR!   run `npm fund` for details
npm ERR!
npm ERR! 4 high severity vulnerabilities
npm ERR!
npm ERR! To address all issues (including breaking changes), run:
npm ERR!   npm audit fix --force
npm ERR!
npm ERR! Run `npm audit` for details.
npm ERR!
npm ERR! > node-datachannel@0.4.0 _prebuild
npm ERR! > prebuild --backend cmake-js
npm ERR!
npm ERR! [
npm ERR!   '/Users/q/Library/Application Support/fnm/node-versions/v19.0.0/installation/bin/node',
npm ERR!   '/Users/q/Desktop/projects/httptoolkit/httptoolkit-server/node_modules/node-datachannel/node_modules/.bin/cmake-js',
npm ERR!   'rebuild',
npm ERR!   '--runtime-version=19.0.0',
npm ERR!   '--arch=arm64',
npm ERR!   '--runtime=node'
npm ERR! ]
npm ERR! Not searching for unused variables given on the command line.
npm ERR! -- The C compiler identification is AppleClang 14.0.0.14000029
npm ERR! -- The CXX compiler identification is AppleClang 14.0.0.14000029
npm ERR! -- Detecting C compiler ABI info
npm ERR! -- Detecting C compiler ABI info - done
npm ERR! -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
npm ERR! -- Detecting C compile features
npm ERR! -- Detecting C compile features - done
npm ERR! -- Detecting CXX compiler ABI info
npm ERR! -- Detecting CXX compiler ABI info - done
npm ERR! -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
npm ERR! -- Detecting CXX compile features
npm ERR! -- Detecting CXX compile features - done
npm ERR! -- Configuring incomplete, errors occurred!
npm ERR! See also "/Users/q/Desktop/projects/httptoolkit/httptoolkit-server/node_modules/node-datachannel/build/CMakeFiles/CMakeOutput.log".
npm ERR! See also "/Users/q/Desktop/projects/httptoolkit/httptoolkit-server/node_modules/node-datachannel/build/CMakeFiles/CMakeError.log".
npm ERR! prebuild-install WARN install No prebuilt binaries found (target=19.0.0 runtime=node arch=arm64 libc= platform=darwin)
npm ERR! npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm ERR! npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
npm ERR! npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm ERR! npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm ERR! npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm ERR! prebuild info begin Prebuild version 11.0.4
npm ERR! prebuild info build Preparing to prebuild node-datachannel@0.4.0 for node 19.0.0 on darwin-arm64 using cmake-js
npm ERR! info TOOL Using Unix Makefiles generator.
npm ERR! info CMD CLEAN
npm ERR! info RUN [
npm ERR! info RUN   'cmake',
npm ERR! info RUN   '-E',
npm ERR! info RUN   'remove_directory',
npm ERR! info RUN   '/Users/q/Desktop/projects/httptoolkit/httptoolkit-server/node_modules/node-datachannel/build'
npm ERR! info RUN ]
npm ERR! info CMD CONFIGURE
npm ERR! info RUN [
npm ERR! info RUN   'cmake',
npm ERR! info RUN   '/Users/q/Desktop/projects/httptoolkit/httptoolkit-server/node_modules/node-datachannel',
npm ERR! info RUN   '--no-warn-unused-cli',
npm ERR! info RUN   '-G',
npm ERR! info RUN   'Unix Makefiles',
npm ERR! info RUN   '-DCMAKE_JS_VERSION=6.3.2',
npm ERR! info RUN   '-DCMAKE_BUILD_TYPE=Release',
npm ERR! info RUN   '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/Users/q/Desktop/projects/httptoolkit/httptoolkit-server/node_modules/node-datachannel/build/Release',
npm ERR! info RUN   '-DCMAKE_JS_INC=/Users/q/.cmake-js/node-arm64/v19.0.0/include/node;/Users/q/Desktop/projects/httptoolkit/httptoolkit-server/node_modules/node-datachannel/node_modules/nan',
npm ERR! info RUN   '-DCMAKE_JS_SRC=',
npm ERR! info RUN   '-DNODE_RUNTIME=node',
npm ERR! info RUN   '-DNODE_RUNTIMEVERSION=19.0.0',
npm ERR! info RUN   '-DNODE_ARCH=arm64',
npm ERR! info RUN   '-DCMAKE_OSX_ARCHITECTURES=arm64',
npm ERR! info RUN   '-DCMAKE_CXX_FLAGS=-D_DARWIN_USE_64_BIT_INODE=1 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DBUILDING_NODE_EXTENSION',
npm ERR! info RUN   '-DCMAKE_SHARED_LINKER_FLAGS=-undefined dynamic_lookup'
npm ERR! info RUN ]
npm ERR! CMake Error at /opt/homebrew/Cellar/cmake/3.25.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
npm ERR!   Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
npm ERR!   system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY
npm ERR!   OPENSSL_INCLUDE_DIR)
npm ERR! Call Stack (most recent call first):
npm ERR!   /opt/homebrew/Cellar/cmake/3.25.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
npm ERR!   /opt/homebrew/Cellar/cmake/3.25.1/share/cmake/Modules/FindOpenSSL.cmake:613 (find_package_handle_standard_args)
npm ERR!   CMakeLists.txt:22 (find_package)
npm ERR!
npm ERR!
npm ERR! ERR! OMG Process terminated: 1
npm ERR! prebuild ERR! build Error: Failed to build cmake with exit code 1
npm ERR! prebuild ERR! build     at ChildProcess.<anonymous> (/Users/q/Desktop/projects/httptoolkit/httptoolkit-server/node_modules/node-datachannel/node_modules/prebuild/cmakebuild.js:32:19)
npm ERR! prebuild ERR! build     at ChildProcess.emit (node:events:513:28)
npm ERR! prebuild ERR! build     at ChildProcess._handle.onexit (node:internal/child_process:293:12)

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/q/.npm/_logs/2022-12-20T17_50_19_095Z-debug-0.log
```

**Comment by pimterry** [comment]
I think that's not using the prebuild because of Node v19, not ARM64. Can you try using node v18 or v16, the LTS versions? Supported platforms are here: https://github.com/murat-dogan/node-datachannel#supported-platforms

(I imagine v19 will have prebuilds soon, in the next node-datachannel release, it's just that there hasn't been a release since v19 was first published in October)

**Comment by pimterry** [comment]
(I've opened a PR for v19 prebuilds here: https://github.com/murat-dogan/node-datachannel/pull/149)

**Comment by shirshak55** [comment]
@pimterry I installed openssl using brew and it worked in node v19, too :)

**Comment by shirshak55** [comment]
@pimterry I think it is cross platform issue, so shouldn't matter anyway

```

npm ERR! prebuild-install WARN install No prebuilt binaries found (target=19.0.0 runtime=node arch=arm64 libc= platform=linux)
npm ERR! sh: prebuild: command not found

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/q/.npm/_logs/2022-12-22T23_55_52_790Z-debug-0.log
    Error: Command failed: /bin/sh -c npm install --production
    Code: 127
Error: Spawn /Users/q/Desktop/projects/httptoolkit/httptoolkit-server/build/build-release.sh linux exited with 1
    at ChildProcess.<anonymous> (/Users/q/Desktop/projects/httptoolkit/httptoolkit-server/pack.ts:16:25)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at Process.ChildProcess._handle.onexit (node:internal/ch
```


Closing it as the core issue is fixed?

**Comment by pimterry** [comment]
Yes, it makes sense that Linux ARM doesn't work, there's definitely no prebuilds for that, it's fairly unusual (although if you want to look at creating those, feel free!)

Prebuilds should never be strictly required though to build & run locally though - they're only important for releases, where we want to use the binaries for a _different_ platform/architecture to the current machine, in which case pulling a known build for that target is very convenient.

For local dev, if prebuilds work that's great, but if not you should always be able to `npm install` regardless, as long as you have a local Node.js native build environment available (including OpenSSL).

> Closing it as the core issue is fixed?

For now I think yes, this can be closed. It's now possible to easily locally run the server on Darwin ARM64, which was the main goal. With a local native build setup (which I expect most Linux users will have) it should also be possible on linux-arm.

I am planning to create official Darwin-ARM64 releases, for both the server & desktop, and offer that directly from the website, but I think we should track that separately in the global issues repo. I'll do that now :smile:
